### ISSUE TITLE
Server source?

### ISSUE THREAD

**Issue by Mistik** [n0uk/glorio-client#7]
Hi

Will the server code also be opened sourced?

**Comment by n0uk** [comment]
Hi! No, we use it on our active project, so it won't be opened.

**Comment by Mistik** [comment]
> Hi! No, we use it on our active project, so it won't be opened. 

Ah ok I thought it was open source there is a clone currently up and they have added several new server side features

https://glar.io

**Comment by Mark3rM** [comment]
can i request a newer version?

**Comment by n0uk** [comment]
@Mark3rM 
No, sorry. We use this server engine in our currently active game: dynast.io, and won't share it.

**Comment by Mark3rM** [comment]
I take it you are a tuberton?

**Comment by Mark3rM** [comment]
и хотелось бы уточнить, мне нужна не самая новая версия, а версия где есть блоки поновее, например блок кристалл, это мне нужно для запуска канала на ютубе, может это поднимет актив игры

**Comment by Mark3rM** [comment]
and I would like to clarify, I don’t need the newest version, but a version where there are newer blocks, for example, a crystal block, I need this to launch a channel on YouTube, maybe this will raise the asset of the game
